In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("kc_house_data.csv")

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
df

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
0             1180      5650     1.0           0     0          3      7   
1             2570      7242     2.0           0     0          3      7   
2              770     10000     1.0           0     0          3      6   
3             1960      5000     1.0           0     0          5      7   
4             1680      8080     1.0           0     0          3      8   
...            ...       ...     ...         ...   ...        ...    ...   
21608         1530      1131     3.0           0     0          3      8   
21609         2310      5813     2.0           0     0          3      8   
21610         1020      1350     2.0           0     0          3      7   
21611         1600      2388     2.0           0     0          3      8   
21612         1020      1076     2.0           0     0          3      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0          1180.0              0      1955             0    98178  47.5112   
1          2170.0            400      1951          1991    98125  47.7210   
2           770.0              0      1933             0    98028  47.7379   
3          1050.0            910      1965             0    98136  47.5208   
4          1680.0              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608      1530.0              0      2009             0    98103  47.6993   
21609      2310.0              0      2014             0    98146  47.5107   
21610      1020.0              0      2009             0    98144  47.5944   
21611      1600.0              0      2004             0    98027  47.5345   
21612      1020.0              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [5]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       2
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [6]:
dfn=df.dropna()

In [7]:
dfn

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
0             1180      5650     1.0           0     0          3      7   
1             2570      7242     2.0           0     0          3      7   
2              770     10000     1.0           0     0          3      6   
3             1960      5000     1.0           0     0          5      7   
4             1680      8080     1.0           0     0          3      8   
...            ...       ...     ...         ...   ...        ...    ...   
21608         1530      1131     3.0           0     0          3      8   
21609         2310      5813     2.0           0     0          3      8   
21610         1020      1350     2.0           0     0          3      7   
21611         1600      2388     2.0           0     0          3      8   
21612         1020      1076     2.0           0     0          3      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0          1180.0              0      1955             0    98178  47.5112   
1          2170.0            400      1951          1991    98125  47.7210   
2           770.0              0      1933             0    98028  47.7379   
3          1050.0            910      1965             0    98136  47.5208   
4          1680.0              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608      1530.0              0      2009             0    98103  47.6993   
21609      2310.0              0      2014             0    98146  47.5107   
21610      1020.0              0      2009             0    98144  47.5944   
21611      1600.0              0      2004             0    98027  47.5345   
21612      1020.0              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21611 rows x 21 columns]

In [8]:
feature_cols = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15']
X=dfn[feature_cols].values

In [9]:
X

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [10]:
Y = dfn.price.values

In [11]:
Y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=1/3,random_state=0)

In [14]:
X_train

array([[ 3.00000e+00,  2.75000e+00,  3.90000e+03, ..., -1.21924e+02,
         2.46000e+03,  2.17800e+05],
       [ 3.00000e+00,  2.25000e+00,  1.82000e+03, ..., -1.22249e+02,
         1.93000e+03,  1.36000e+04],
       [ 4.00000e+00,  1.75000e+00,  1.43000e+03, ..., -1.22184e+02,
         1.03000e+03,  5.90000e+03],
       ...,
       [ 5.00000e+00,  2.00000e+00,  1.91000e+03, ..., -1.22306e+02,
         1.23000e+03,  2.54500e+03],
       [ 3.00000e+00,  2.25000e+00,  1.48000e+03, ..., -1.22342e+02,
         1.31000e+03,  1.32900e+03],
       [ 4.00000e+00,  1.75000e+00,  2.34000e+03, ..., -1.22108e+02,
         2.47000e+03,  1.10000e+04]])

In [15]:
Y_train

array([415000., 480000., 265000., ..., 650000., 436000., 700000.])

# Linear Regression

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
y_pred=regressor.predict(X_test)

In [19]:
y_pred

array([ 82349.76224528, 334757.86934179, 903342.38908868, ...,
       893356.97230532, 544091.4496214 , 621932.12462916])

In [20]:
from sklearn.metrics import r2_score

r2score_LR=r2_score(Y_test,y_pred)
r2score_LR

0.6852737150804505

# MultipleLinearRegression

In [21]:
import statsmodels.api as sm

In [22]:
X=np.append(arr=np.ones((21611,1)).astype(int),values=X,axis=1)

In [23]:
X

array([[ 1.00000e+00,  3.00000e+00,  1.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 1.00000e+00,  3.00000e+00,  2.25000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 1.00000e+00,  3.00000e+00,  2.50000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [24]:
x_opt=X [:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]]  
regressor_OLS=sm.OLS(endog = Y, exog=x_opt).fit()  
regressor_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.684
Model:                            OLS   Adj. R-squared:                  0.684
Method:                 Least Squares   F-statistic:                     3113.
Date:                Tue, 19 May 2020   Prob (F-statistic):               0.00
Time:                        21:46:32   Log-Likelihood:            -2.9514e+05
No. Observations:               21611   AIC:                         5.903e+05
Df Residuals:                   21595   BIC:                         5.904e+05
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       7.006e+06   3.01e+06      2.330      0.020    1.11e+06    1.29e+07
x1         -3.822e+04   1937.822    -19.721      0.000    -4.2e+04   -3.44e+04
x2          4.102e+04   3338.104     12.288      0.000    3.45e+04    4.76e+04
x3           111.9753      2.326     48.132      0.000     107.415     116.535
x4            -0.0587      0.036     -1.647      0.100      -0.129       0.011
x5          7715.8294   3688.157      2.092      0.036     486.770    1.49e+04
x6           7.97e+04   2036.217     39.140      0.000    7.57e+04    8.37e+04
x7          2.698e+04   2412.881     11.183      0.000    2.23e+04    3.17e+04
x8          9.441e+04   2207.929     42.760      0.000    9.01e+04    9.87e+04
x9            73.9974      2.308     32.060      0.000      69.473      78.521
x10           37.9781      2.716     13.982      0.000      32.654      43.302
x11        -2595.9069     74.558    -34.817      0.000   -2742.046   -2449.768
x12           26.3547      3.746      7.036      0.000      19.013      33.696
x13         -601.7475     33.849    -17.777      0.000    -668.095    -535.400
x14          6.01e+05    1.1e+04     54.568      0.000    5.79e+05    6.23e+05
x15         -2.28e+05   1.34e+04    -16.977      0.000   -2.54e+05   -2.02e+05
x16           17.5050      3.533      4.955      0.000      10.581      24.429
==============================================================================
Omnibus:                    19170.644   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2013822.416
Skew:                           3.820   Prob(JB):                         0.00
Kurtosis:                      49.670   Cond. No.                     6.54e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.01e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [25]:
x_opt=X [:, [0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16]]  
regressor_OLS=sm.OLS(endog = Y, exog=x_opt).fit()  
regressor_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.684
Model:                            OLS   Adj. R-squared:                  0.684
Method:                 Least Squares   F-statistic:                     3335.
Date:                Tue, 19 May 2020   Prob (F-statistic):               0.00
Time:                        21:46:32   Log-Likelihood:            -2.9514e+05
No. Observations:               21611   AIC:                         5.903e+05
Df Residuals:                   21596   BIC:                         5.904e+05
Df Model:                          14                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6.524e+06   2.99e+06      2.180      0.029    6.59e+05    1.24e+07
x1         -3.796e+04   1931.789    -19.651      0.000   -4.17e+04   -3.42e+04
x2          4.109e+04   3337.963     12.309      0.000    3.45e+04    4.76e+04
x3           111.5549      2.312     48.241      0.000     107.022     116.088
x4          8102.9099   3680.807      2.201      0.028     888.257    1.53e+04
x5          7.953e+04   2033.778     39.105      0.000    7.55e+04    8.35e+04
x6          2.702e+04   2412.862     11.199      0.000    2.23e+04    3.18e+04
x7           9.44e+04   2208.008     42.753      0.000    9.01e+04    9.87e+04
x8            73.5721      2.294     32.076      0.000      69.076      78.068
x9            37.9836      2.716     13.983      0.000      32.659      43.308
x10        -2590.2125     74.481    -34.777      0.000   -2736.200   -2444.225
x11           26.3935      3.746      7.047      0.000      19.052      33.735
x12         -602.2995     33.849    -17.794      0.000    -668.646    -535.953
x13         6.022e+05    1.1e+04     54.807      0.000    5.81e+05    6.24e+05
x14        -2.318e+05   1.32e+04    -17.521      0.000   -2.58e+05   -2.06e+05
x15           17.7539      3.530      5.030      0.000      10.836      24.672
==============================================================================
Omnibus:                    19194.988   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2025985.173
Skew:                           3.827   Prob(JB):                         0.00
Kurtosis:                      49.812   Cond. No.                     6.41e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.07e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

# PolynomialRegression

In [26]:
from sklearn.preprocessing import PolynomialFeatures 
  
poly = PolynomialFeatures(degree = 2) 
X_poly = poly.fit_transform(X) 

In [27]:
X_poly

array([[1.0000000e+00, 1.0000000e+00, 3.0000000e+00, ..., 1.7956000e+06,
        7.5710000e+06, 3.1922500e+07],
       [1.0000000e+00, 1.0000000e+00, 3.0000000e+00, ..., 2.8561000e+06,
        1.2909910e+07, 5.8354321e+07],
       [1.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 7.3984000e+06,
        2.1928640e+07, 6.4995844e+07],
       ...,
       [1.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 1.0404000e+06,
        2.0471400e+06, 4.0280490e+06],
       [1.0000000e+00, 1.0000000e+00, 3.0000000e+00, ..., 1.9881000e+06,
        1.8146700e+06, 1.6563690e+06],
       [1.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 1.0404000e+06,
        1.3841400e+06, 1.8414490e+06]])

In [28]:
poly.fit(X_poly, Y) 
lin2 = LinearRegression() 
lin2.fit(X_poly, Y) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
y_pred=lin2.predict(poly.fit_transform(X))

In [30]:
y_pred

array([286257.72434044, 609569.88314247, 450773.18058968, ...,
       423394.63459015, 456979.04130363, 420950.40106964])

In [31]:
r2score_PR=r2_score(Y,y_pred)
r2score_PR

0.8084274210389774

# SVR

In [32]:
Y=Y.reshape(-1,1)
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
X1=sc_x.fit_transform(X)
Y1=sc_y.fit_transform(Y)

In [33]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(X1,Y1)

C:\Users\LEENA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\LEENA\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [34]:
y_pred = sc_y.inverse_transform ((regressor.predict (sc_x.transform(np.array(X1)))))

In [35]:
y_pred

array([800806.39272978, 800806.39272978, 800806.39272978, ...,
       800806.39272978, 800806.39272978, 800806.39272978])

In [36]:
r2score_SVR=r2_score(Y1,sc_y.inverse_transform ((regressor.predict (sc_x.transform(np.array(X1))))))
r2score_SVR

-641290878636.8857

# RandomForest

In [37]:
from sklearn.ensemble import RandomForestRegressor

In [38]:
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X,Y)
y_pred = regressor.predict(X)

C:\Users\LEENA\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [39]:
y_pred

array([237270.4, 483822.5, 209850. , ..., 368204.4, 394400. , 341511.6])

In [40]:
r2score_RF=r2_score(Y,y_pred)
r2score_RF

0.9771471033552779

# DecisionTree

In [41]:
from sklearn.tree import DecisionTreeRegressor

In [42]:
regressor = DecisionTreeRegressor(random_state=0)#,criterion='mae'
regressor.fit(X, Y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [43]:
y_pred = regressor.predict(X)

In [44]:
y_pred

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [45]:
r2score_DT=r2_score(Y,y_pred)
r2score_DT

0.9991338236961734

# XGBoost

In [46]:
from xgboost import XGBRegressor
regressor=XGBRegressor()
regressor.fit(X_train,Y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [47]:
y_pred=regressor.predict(X_test)

In [48]:
y_pred

array([181657.17, 443497.78, 823263.5 , ..., 652496.44, 552079.25,
       430157.38], dtype=float32)

In [49]:
r2_score(Y,y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [21611, 7204]

# Result

In [51]:
results = pd.DataFrame({
    'Model': ['Linear Regression','PolynomialRegression','SVR','RandomForest','DecisionTree',
              ],
    'Score': [r2score_LR,r2score_PR, r2score_SVR, r2score_RF, 
              r2score_DT]})
result_df = results.sort_values(by='Score', ascending=False)
result_df = result_df.set_index('Score')
result_df

Model
Score                              
 9.991338e-01          DecisionTree
 9.771471e-01          RandomForest
 8.084274e-01  PolynomialRegression
 6.852737e-01     Linear Regression
-6.412909e+11                   SVR